# Utiliza a imagem oficial do PostgreSQL 
FROM postgres:15

# Copia o arquivo schema.sql com a modelagem de ativos e aposentados para a pasta de inicialização
COPY schema.sql /docker-entrypoint-initdb.d/